DROP table if exists book_legislators_current;

CREATE table book_legislators_current
(
record_number int
,id_bioguide varchar
,id_thomas float
,id_lis varchar
,id_govtrack float
,id_opensecrets varchar
,id_votesmart float
,id_fec_0 varchar
,id_fec_1 varchar
,id_cspan float
,id_wikipedia varchar
,id_house_history float
,id_ballotpedia varchar
,id_maplight float
,id_icpsr float
,id_wikidata varchar
,id_google_entity_id varchar
,name_first varchar
,name_last varchar
,name_official_full varchar
,bio_birthday date
,bio_gender char(1)
,terms_0_type varchar
,terms_0_start date
,terms_0_end date
,terms_0_state varchar
,terms_0_district float
,terms_0_party varchar
,terms_1_type varchar
,terms_1_start date
,terms_1_end date
,terms_1_state varchar
,terms_1_district float
,terms_1_party varchar
,terms_2_type varchar
,terms_2_start date
,terms_2_end date
,terms_2_state varchar
,terms_2_district float
,terms_2_party varchar
,terms_3_type varchar
,terms_3_start date
,terms_3_end date
,terms_3_state varchar
,terms_3_district float
,terms_3_party varchar
,terms_4_type varchar
,terms_4_start date
,terms_4_end date
,terms_4_state varchar
,terms_4_district float
,terms_4_party varchar
,terms_5_type varchar
,terms_5_start date
,terms_5_end date
,terms_5_state varchar
,terms_5_district float
,terms_5_party varchar
,terms_5_url varchar
,terms_6_type varchar
,terms_6_start date
,terms_6_end date
,terms_6_state varchar
,terms_6_district float
,terms_6_party varchar
,terms_6_url varchar
,terms_7_type varchar
,terms_7_start date
,terms_7_end date
,terms_7_state varchar
,terms_7_class float
,terms_7_party varchar
,terms_7_url varchar
,terms_7_address varchar
,terms_7_phone varchar
,terms_7_fax varchar
,terms_7_contact_form varchar
,terms_7_office varchar
,terms_8_type varchar
,terms_8_start date
,terms_8_end date
,terms_8_state varchar
,terms_8_party varchar
,terms_8_class float
,terms_8_url varchar
,terms_8_address varchar
,terms_8_phone varchar
,terms_8_fax varchar
,terms_8_contact_form varchar
,terms_8_office varchar
,terms_8_state_rank varchar
,terms_8_rss_url varchar
,terms_9_type varchar
,terms_9_start date
,terms_9_end date
,terms_9_state varchar
,terms_9_class float
,terms_9_party varchar
,terms_9_state_rank varchar
,terms_9_url varchar
,terms_9_rss_url varchar
,terms_9_contact_form varchar
,terms_9_address varchar
,terms_9_office varchar
,terms_9_phone varchar
,terms_1_class float
,terms_1_url varchar
,terms_2_class float
,terms_2_url varchar
,terms_2_address varchar
,terms_2_phone varchar
,terms_2_fax varchar
,terms_2_contact_form varchar
,terms_2_office varchar
,terms_3_class float
,terms_3_url varchar
,terms_3_address varchar
,terms_3_phone varchar
,terms_3_fax varchar
,terms_3_contact_form varchar
,terms_3_office varchar
,terms_3_state_rank varchar
,terms_3_rss_url varchar
,terms_4_class float
,terms_4_state_rank varchar
,terms_4_url varchar
,terms_4_rss_url varchar
,terms_4_contact_form varchar
,terms_4_address varchar
,terms_4_office varchar
,terms_4_phone varchar
,name_middle varchar
,terms_7_district float
,terms_8_district float
,terms_9_district float
,terms_10_type varchar
,terms_10_start date
,terms_10_end date
,terms_10_state varchar
,terms_10_class float
,terms_10_party varchar
,terms_10_url varchar
,terms_10_address varchar
,terms_10_phone varchar
,terms_10_fax varchar
,terms_10_contact_form varchar
,terms_10_office varchar
,terms_11_type varchar
,terms_11_start date
,terms_11_end date
,terms_11_state varchar
,terms_11_party varchar
,terms_11_class float
,terms_11_url varchar
,terms_11_address varchar
,terms_11_phone varchar
,terms_11_fax varchar
,terms_11_contact_form varchar
,terms_11_office varchar
,terms_11_state_rank varchar
,terms_11_rss_url varchar
,terms_12_type varchar
,terms_12_start date
,terms_12_end date
,terms_12_state varchar
,terms_12_class float
,terms_12_party varchar
,terms_12_state_rank varchar
,terms_12_url varchar
,terms_12_rss_url varchar
,terms_12_contact_form varchar
,terms_12_address varchar
,terms_12_office varchar
,terms_12_phone varchar
,terms_5_class float
,terms_6_class float
,terms_6_address varchar
,terms_6_phone varchar
,terms_6_fax varchar
,terms_6_contact_form varchar
,terms_6_office varchar
,terms_7_state_rank varchar
,terms_7_rss_url varchar
,name_nickname varchar
,name_suffix varchar
,terms_0_class float
,terms_0_url varchar
,terms_0_address varchar
,terms_0_phone varchar
,terms_0_fax varchar
,terms_0_contact_form varchar
,terms_0_office varchar
,terms_1_address varchar
,terms_1_phone varchar
,terms_1_fax varchar
,terms_1_contact_form varchar
,terms_1_office varchar
,terms_1_state_rank varchar
,terms_1_rss_url varchar
,terms_2_state_rank varchar
,terms_2_rss_url varchar
,terms_4_fax varchar
,terms_5_state_rank varchar
,terms_5_rss_url varchar
,terms_5_contact_form varchar
,terms_5_address varchar
,terms_5_office varchar
,terms_5_phone varchar
,leadership_roles_0_title varchar
,leadership_roles_0_chamber varchar
,leadership_roles_0_start date
,other_names_0_last varchar
,terms_7_how varchar
,terms_9_fax varchar
,terms_10_state_rank varchar
,terms_10_rss_url varchar
,terms_0_caucus varchar
,terms_1_caucus varchar
,terms_2_caucus varchar
,terms_3_caucus varchar
,terms_4_caucus varchar
,terms_5_caucus varchar
,terms_6_caucus varchar
,terms_7_caucus varchar
,terms_8_caucus varchar
,terms_9_caucus varchar
,terms_10_caucus varchar
,terms_0_how varchar
,leadership_roles_0_end date
,leadership_roles_1_title varchar
,leadership_roles_1_chamber varchar
,leadership_roles_1_start date
,leadership_roles_1_end date
,leadership_roles_2_title varchar
,leadership_roles_2_chamber varchar
,leadership_roles_2_start date
,leadership_roles_2_end date
,leadership_roles_3_title varchar
,leadership_roles_3_chamber varchar
,leadership_roles_3_start date
,leadership_roles_3_end date
,leadership_roles_4_title varchar
,leadership_roles_4_chamber varchar
,leadership_roles_4_start date
,leadership_roles_4_end date
,leadership_roles_5_title varchar
,leadership_roles_5_chamber varchar
,leadership_roles_5_start date
,leadership_roles_5_end date
,leadership_roles_6_title varchar
,leadership_roles_6_chamber varchar
,leadership_roles_6_start date
,leadership_roles_6_end date
,leadership_roles_7_title varchar
,leadership_roles_7_chamber varchar
,leadership_roles_7_start date
,terms_5_fax varchar
,terms_6_state_rank varchar
,terms_6_rss_url varchar
,terms_0_state_rank varchar
,terms_0_rss_url varchar
,family_0_name varchar
,family_0_relation varchar
,family_1_name varchar
,family_1_relation varchar
,family_2_name varchar
,family_2_relation varchar
,family_3_name varchar
,family_3_relation varchar
,terms_2_how varchar
,terms_10_district float
,terms_11_district float
,terms_4_party_affiliations_0_start date
,terms_4_party_affiliations_0_end date
,terms_4_party_affiliations_0_party varchar
,terms_4_party_affiliations_1_start date
,terms_4_party_affiliations_1_end date
,terms_4_party_affiliations_1_party varchar
,terms_4_party_affiliations_2_start date
,terms_4_party_affiliations_2_end date
,terms_4_party_affiliations_2_party varchar
,terms_12_district float
,terms_12_fax varchar
,terms_13_type varchar
,terms_13_start date
,terms_13_end date
,terms_13_state varchar
,terms_13_district float
,terms_13_party varchar
,terms_13_phone varchar
,terms_13_address varchar
,terms_13_office varchar
,terms_13_url varchar
,terms_13_rss_url varchar
,id_fec_2 varchar
,terms_13_fax varchar
,terms_14_type varchar
,terms_14_start date
,terms_14_end date
,terms_14_state varchar
,terms_14_district float
,terms_14_party varchar
,terms_14_phone varchar
,terms_14_address varchar
,terms_14_office varchar
,terms_14_url varchar
,terms_14_rss_url varchar
,terms_13_contact_form varchar
,terms_14_contact_form varchar
,terms_15_type varchar
,terms_15_start date
,terms_15_end date
,terms_15_state varchar
,terms_15_district float
,terms_15_party varchar
,terms_15_phone varchar
,terms_15_url varchar
,terms_15_rss_url varchar
,terms_15_address varchar
,terms_15_office varchar
,terms_16_type varchar
,terms_16_start date
,terms_16_end date
,terms_16_state varchar
,terms_16_district float
,terms_16_party varchar
,terms_16_phone varchar
,terms_16_address varchar
,terms_16_office varchar
,terms_16_url varchar
,terms_16_rss_url varchar
,terms_14_fax varchar
,terms_15_fax varchar
,terms_15_contact_form varchar
,terms_16_fax varchar
,terms_16_contact_form varchar
,terms_17_type varchar
,terms_17_start date
,terms_17_end date
,terms_17_state varchar
,terms_17_party varchar
,terms_17_district float
,terms_17_url varchar
,terms_17_address varchar
,terms_17_phone varchar
,terms_17_fax varchar
,terms_17_contact_form varchar
,terms_17_office varchar
,terms_17_rss_url varchar
,terms_18_type varchar
,terms_18_start date
,terms_18_end date
,terms_18_state varchar
,terms_18_district float
,terms_18_party varchar
,terms_18_phone varchar
,terms_18_url varchar
,terms_18_rss_url varchar
,terms_18_address varchar
,terms_18_office varchar
,terms_18_fax varchar
,terms_19_type varchar
,terms_19_start date
,terms_19_end date
,terms_19_state varchar
,terms_19_district float
,terms_19_party varchar
,terms_19_phone varchar
,terms_19_address varchar
,terms_19_office varchar
,terms_19_url varchar
,terms_19_rss_url varchar
,terms_18_contact_form varchar
,terms_19_fax varchar
,terms_19_contact_form varchar
,terms_20_type varchar
,terms_20_start date
,terms_20_end date
,terms_20_state varchar
,terms_20_party varchar
,terms_20_class float
,terms_20_state_rank varchar
,terms_20_url varchar
,terms_20_phone varchar
,terms_20_office varchar
,terms_20_address varchar
,terms_20_contact_form varchar
,terms_21_type varchar
,terms_21_start date
,terms_21_end date
,terms_21_state varchar
,terms_21_party varchar
,terms_21_class float
,terms_21_state_rank varchar
,terms_21_url varchar
,terms_21_phone varchar
,terms_21_office varchar
,terms_21_address varchar
,terms_21_contact_form varchar
,terms_0_party_affiliations_0_start date
,terms_0_party_affiliations_0_end date
,terms_0_party_affiliations_0_party varchar
,terms_0_party_affiliations_1_start date
,terms_0_party_affiliations_1_end date
,terms_0_party_affiliations_1_party varchar
,terms_1_how varchar
,terms_20_district float
,terms_20_rss_url varchar
,terms_5_party_affiliations_0_start date
,terms_5_party_affiliations_0_end date
,terms_5_party_affiliations_0_party varchar
,terms_5_party_affiliations_1_start date
,terms_5_party_affiliations_1_end date
,terms_5_party_affiliations_1_party varchar
,terms_20_fax varchar
,terms_21_district float
,terms_21_fax varchar
,terms_21_rss_url varchar
,terms_22_type varchar
,terms_22_start date
,terms_22_end date
,terms_22_state varchar
,terms_22_district float
,terms_22_party varchar
,terms_22_phone varchar
,terms_22_url varchar
,terms_22_rss_url varchar
,terms_22_address varchar
,terms_22_office varchar
,terms_22_fax varchar
,terms_23_type varchar
,terms_23_start date
,terms_23_end date
,terms_23_state varchar
,terms_23_district float
,terms_23_party varchar
,terms_23_phone varchar
,terms_23_address varchar
,terms_23_office varchar
,terms_23_url varchar
,terms_23_rss_url varchar
,family_4_name varchar
,family_4_relation varchar
,terms_0_end_type varchar
)
;

COPY book_legislators_current
FROM '/Users/ctanimura/Documents/Projects/SQL Book/legislators-current_flat.csv'
DELIMITER ','
CSV HEADER
;
